apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-service-secret
  namespace: auth-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: auth-service-secret
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: auth-service-dev/database-url
    - secretKey: MASTER_KEY
      remoteRef:
        key: auth-service-dev/master-key
